[package]
name = "macros"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
safe-vk = { path = "../../safe-vk", features = ["macros"] }
tokio = { version = "1.0", features = ["full"] }
