[package]
name = "reply"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
safe-vk = { path = "../../safe-vk", features = ["macros"] }
serde_json = "1.0.117"
serde = "1.0.203"
rand = { version = "0.8.5", features = ["small_rng"] }
tokio = { version = "1", features = ["full"] }
