[package]
name = "oobabooga"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0.117"
reqwest = { version = "0.12.4", features = ["json", "stream"] }
safe-vk = { path = "../../safe-vk" }
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3.30"
